### ISSUE TITLE
Bug in INCHandler

### ISSUE THREAD

**Issue by w67clement** [ImmaFreedom-Dev/MineAPI#1]
Hello, I have find in MineAPI a bug in INCHandler, it is very very important, why? This bug has the effect of creating a malfunction in ping packets after reload.
 
The new code is here: https://github.com/w67clement/MineAPI/blob/master/src/main/java/com/w67clement/mineapi/system/event/INCHandler.java

The difference can be view here: https://github.com/w67clement/MineAPI/commit/f2c5fb36cdbd6f109d1cff4a06d47928ef2f3962

Thank you to update this portion of code.

PS: I can't create a pull request, it is the why I created a Issue report.

**Comment by LegendIsAwesomes** [comment]
Sorry a PR must be needed.

**Comment by RobinGall2910** [comment]
Associated PR #2 is open.

**Comment by w67clement** [comment]
The pull request is merged!
The issue can be closed.
